# Site settings
title: Alpha
SEOTitle: 张建的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: mengzhangjian@gmail.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 张建的博客, 张建, 计算机视觉, 机器人,Computer Vision"
url: "http://mengzhangjian.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/mengzhangjian/mengzhangjian.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "改变，行动，自律!"
sidebar-avatar: /img/avatar-by.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     alphaxone
github_username:    mengzhangjian
facebook_username:  100006075480199
jianshu_username:   33abd4ccb0fc
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
 #Disqus（https://disqus.com/）
 #disqus_username: mengzhangjian

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID:  6ff1a0fe3ca5d250981c                           #生成的clientID
  clientSecret: 3095f95a2ac5a609b4641e07ea0cd98547a6897f    #生成的clientSecret
  repo: mengzhangjian.github.io    #仓库名称
  owner: mengzhangjian    #github用户名
  admin: [mengzhangjian]
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-121837119-1'            # Format: UA-xxxxxx-xx
ga_domain: alphaxone.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
